[package]
name = "ficherors"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
chrono = "0.4.24"
regex = "1.7.3"
rand = "0.8.5"
calamine = "0.23.1"
simple-error = "0.3.0"